ARG BUILDER_IMAGE

FROM ${BUILDER_IMAGE}

RUN sudo apk add git bash build-base && \
    go get -u github.com/gobuffalo/packr/v2/packr2

COPY --chown=app . /go/src/github.com/ory/oathkeeper

ARG VERSION=unknown
ARG REVISION=unknown
ARG CGO_ENABLED=1

WORKDIR /go/src/github.com/ory/oathkeeper

RUN VERSION=${VERSION} REVISION=${REVISION} CGO_ENABLED=${CGO_ENABLED} make build
